[package]
name = "rustyhack_client"
version = "0.2.0"
authors = ["pbellchambers <pbellchambers@users.noreply.github.com>"]
edition = "2018"
repository = "https://github.com/pbellchambers/rustyhack-mmo"
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyhack_lib = { path = "../rustyhack_lib" }
log = "0.4.14"
simplelog = "0.10.0"
console_engine = "1.5.1"
crossterm = { version = "0.20.0", features = ["serde"] }
laminar = "0.5.0"
crossbeam-channel = "0.5.1"
serde = { version = "1.0.125", features = ["derive"] }
bincode = "1.3.1"
regex = "1.4.5"
chrono = "0.4.19"