[package]
name = "rustyhack_lib"
version = "0.2.0"
authors = ["pbellchambers <pbellchambers@users.noreply.github.com>"]
edition = "2018"
repository = "https://github.com/pbellchambers/rustyhack-mmo"
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
simplelog = "0.10.0"
serde = { version = "1.0.125", features = ["derive"] }
console_engine = "2.0.1"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
strum = "0.20.0"
strum_macros = "0.20.1"